# mkdir -p ~/.config/starship.toml && curl -s https://raw.githubusercontent.com/xUNiiTY/Backup/refs/heads/main/Terminal/starship.toml >> ~/.config/starship.toml


# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[╭╴](238)$env_var\
$all[╰─](238)$character"""

# Change the default prompt characters
[character]
success_symbol = "[✔](238)"
error_symbol = "[✖](238)"

[os]
format = " [$symbol]($style)"
style = "white"

disabled = false
[os.symbols]
Windows = " "
Ubuntu = " "
Macos = ""
Arch = "Arch is the best! "


[localip]
ssh_only = false
format = "[$localipv4](bold yellow) "
disabled = false


[username]
style_user = "white"
style_root = "black bold"
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)@[$hostname](bold red) '
ssh_symbol = "󰞷 "
